#!/usr/bin/env bash
# Build every allocator variant and run the whole roofline matrix.
#
#   run-all.sh [step...]     steps: build matrix tierup shim report (default: all)
#
# Outputs (all under bench/roofline):
#   target/dist/<variant>-<profile>.wasm         wasm32-unknown-unknown cdylib
#   target/dist/<variant>-<profile>-wasi.wasm    wasm32-wasip1 self-timing binary
#   target/dist/<variant>-<profile>-native       host build of the same binary
#   results/<engine>-<tier>-<variant>.json       the matrix
#   results/tierup-<engine>-<variant>-n<N>.json  calls until V8 leaves Liftoff
#   results/flagcheck-*.json                     which V8 flags really pin Liftoff
#   results/shim-<engine>-<tier>-<profile>-<variant>.json   shim/LTO study
#   results/shim-inspect.txt                     call structure of the hot loops
#   results/REPORT.md                            tables generated by report.mjs
#
# Environment overrides: NODE D8 JSC WASMTIME WASM_OPT WASM_TOOLS, ROOFLINE_VARIANTS
# (space-separated subset of the variants), ROOFLINE_CPUS
# (taskset list, default 4-7, empty to disable pinning), ROOFLINE_MEM (default
# 4G), ROOFLINE_TIMEOUT (default 20m), ROOFLINE_REPS (default 7). Every engine
# run goes through scripts/memlimit.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
cd "$here"

NODE="${NODE:-node}"
D8="${D8:-$HOME/.jsvu/bin/v8-15.2.124}"
JSC="${JSC:-$HOME/.jsvu/bin/jsc}"
WASMTIME="${WASMTIME:-$HOME/.wasmtime/bin/wasmtime}"
WASM_OPT="${WASM_OPT:-wasm-opt}"
WASM_TOOLS="${WASM_TOOLS:-wasm-tools}"
CPUS="${ROOFLINE_CPUS-4-7}"
MEM="${ROOFLINE_MEM:-4G}"
TIMEOUT="${ROOFLINE_TIMEOUT:-20m}"
REPS="${ROOFLINE_REPS:-7}"

# ROOFLINE_VARIANTS="sizeclass dlmalloc" restricts build and matrix to a subset.
read -r -a VARIANTS <<< "${ROOFLINE_VARIANTS:-bump freelist sizeclass pages dlmalloc talc lol_alloc}"
# talc and lol_alloc only build for wasm; the host default is libc malloc.
NATIVE_VARIANTS=()
for v in "${VARIANTS[@]}"; do
  case "$v" in talc|lol_alloc) ;; *) NATIVE_VARIANTS+=("$v") ;; esac
done
SHIM_VARIANTS=(dlmalloc sizeclass)
SHIM_PROFILES=(release release-nolto release-z release-z-nolto)
SHIM_WORKLOADS=alloc_free_32,churn
TIERUP_VARIANTS=(bump sizeclass dlmalloc)
TIERUP_N=(1 10 100 1000 10000 100000)

DIST="$here/target/dist"
RESULTS="$here/results"
mkdir -p "$DIST" "$RESULTS"

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
limit() { "$repo/scripts/memlimit" -m "$MEM" -t "$TIMEOUT" -- "$@"; }
pinned() {
  if [ -n "$CPUS" ]; then limit taskset -c "$CPUS" "$@"; else limit "$@"; fi
}
# The dlmalloc variant is the std default: no feature flag.
features() { if [ "$1" != dlmalloc ]; then echo "--features $1"; fi; }

# ---------------------------------------------------------------- build

build_wasm() { # variant profile
  local v=$1 p=$2
  # shellcheck disable=SC2046
  limit cargo build --quiet --profile "$p" --target wasm32-unknown-unknown --lib $(features "$v")
  cp "target/wasm32-unknown-unknown/$p/roofline.wasm" "$DIST/$v-$p.wasm"
}

build_wasi() { # variant profile
  local v=$1 p=$2
  # shellcheck disable=SC2046
  limit cargo build --quiet --profile "$p" --target wasm32-wasip1 --bin roofline-wasi $(features "$v")
  cp "target/wasm32-wasip1/$p/roofline-wasi.wasm" "$DIST/$v-$p-wasi.wasm"
}

build_native() { # variant profile
  local v=$1 p=$2
  # shellcheck disable=SC2046
  limit cargo build --quiet --profile "$p" --bin roofline-wasi $(features "$v")
  cp "target/$p/roofline-wasi" "$DIST/$v-$p-native"
}

step_build() {
  for v in "${VARIANTS[@]}"; do
    log "build $v (release): wasm32-unknown-unknown, wasm32-wasip1"
    build_wasm "$v" release
    build_wasi "$v" release
  done
  for v in "${NATIVE_VARIANTS[@]}"; do
    log "build $v (release): native"
    build_native "$v" release
  done
  for v in "${SHIM_VARIANTS[@]}"; do
    for p in "${SHIM_PROFILES[@]}"; do
      log "build $v ($p): wasm32-unknown-unknown"
      build_wasm "$v" "$p"
      # Post-processed with wasm-opt as wasm-bindgen/wasm-pack users do.
      limit "$WASM_OPT" -O3 --all-features "$DIST/$v-$p.wasm" -o "$DIST/$v-$p-wasmopt.wasm"
    done
  done
  ls -l "$DIST" >&2
}

# ---------------------------------------------------------------- engines

node_version() { "$NODE" -p 'process.versions.node' 2>/dev/null; }
node_v8_version() { "$NODE" -p 'process.versions.v8' 2>/dev/null; }
d8_version() { "$D8" -e 'print(version())' 2>/dev/null; }
jsc_version() {
  local rev=""
  if [ -f "$HOME/.jsvu/status.json" ]; then
    rev="$(jq -r '.javascriptcore // empty' "$HOME/.jsvu/status.json" 2>/dev/null || true)"
  fi
  if [ -n "$rev" ]; then echo "JavaScriptCore r$rev (jsvu)"; else echo "JavaScriptCore"; fi
}
wasmtime_version() { "$WASMTIME" --version; }

# Add engine identity to the self-timed JSON (the module cannot know it).
annotate() { # engine version flags < json > json
  "$NODE" -e '
    const [engine, version, flags] = process.argv.slice(1);
    let s = "";
    process.stdin.on("data", (d) => (s += d)).on("end", () => {
      const j = JSON.parse(s);
      j.engine = engine; j.engineVersion = version; j.flags = flags;
      process.stdout.write(JSON.stringify(j, null, 2) + "\n");
    });' "$@"
}

# run_node TIER VARIANT WASM OUT [v8 flags...]
run_node() {
  local tier=$1 v=$2 wasm=$3 out=$4; shift 4
  local hint=any; [ "$tier" = liftoff ] && hint=liftoff
  pinned "$NODE" --allow-natives-syntax "$@" run.mjs --json --reps "$REPS" --tier-hint "$hint" \
    --flags "${*:-(default)}" "$wasm" > "$out"
}

run_d8() {
  local tier=$1 v=$2 wasm=$3 out=$4; shift 4
  local hint=any; [ "$tier" = liftoff ] && hint=liftoff
  pinned "$D8" --allow-natives-syntax "$@" run-shell.js -- --json --reps "$REPS" --tier-hint "$hint" \
    --flags "${*:-(default)}" "$wasm" > "$out"
}

run_jsc() {
  local v=$1 wasm=$2 out=$3
  pinned "$JSC" run-shell.js -- --json --reps "$REPS" --engine-version "$(jsc_version)" \
    --flags "(default)" "$wasm" > "$out"
}

run_wasmtime() {
  local v=$1 wasm=$2 out=$3
  pinned "$WASMTIME" run "$wasm" --json --reps "$REPS" \
    | annotate wasmtime "$(wasmtime_version)" "(default: cranelift)" > "$out"
}

run_native() {
  local v=$1 bin=$2 out=$3
  pinned "$bin" --json --reps "$REPS" \
    | annotate native "$(uname -m) $(uname -sr)" "(none)" > "$out"
}

# ---------------------------------------------------------------- matrix

step_matrix() {
  local nv="node $(node_version) / V8 $(node_v8_version)" dv="V8 $(d8_version)"
  log "engines: $nv; d8 $dv; $(jsc_version); $(wasmtime_version)"
  for v in "${VARIANTS[@]}"; do
    local wasm="$DIST/$v-release.wasm" wasi="$DIST/$v-release-wasi.wasm"
    log "matrix $v: node default/liftoff/turbofan"
    run_node default "$v" "$wasm" "$RESULTS/node-default-$v.json"
    run_node liftoff "$v" "$wasm" "$RESULTS/node-liftoff-$v.json" --liftoff-only
    run_node turbofan "$v" "$wasm" "$RESULTS/node-turbofan-$v.json" --no-liftoff
    log "matrix $v: d8 default/liftoff/turbofan"
    run_d8 default "$v" "$wasm" "$RESULTS/d8-default-$v.json"
    run_d8 liftoff "$v" "$wasm" "$RESULTS/d8-liftoff-$v.json" --liftoff-only
    run_d8 turbofan "$v" "$wasm" "$RESULTS/d8-turbofan-$v.json" --no-liftoff
    log "matrix $v: jsc default"
    run_jsc "$v" "$wasm" "$RESULTS/jsc-default-$v.json"
    log "matrix $v: wasmtime"
    run_wasmtime "$v" "$wasi" "$RESULTS/wasmtime-cranelift-$v.json"
  done
  for v in "${NATIVE_VARIANTS[@]}"; do
    log "matrix $v: native"
    run_native "$v" "$DIST/$v-release-native" "$RESULTS/native-$(uname -m)-$v.json"
  done
}

# ---------------------------------------------------------------- tier-up

step_tierup() {
  # Which flag recipe actually pins Liftoff? The v8.dev documentation says
  # --liftoff --no-wasm-tier-up; on current V8 dynamic tiering is a separate
  # flag and --liftoff-only is the reliable switch. Record the tier the harness
  # observed under each recipe.
  for v in sizeclass dlmalloc; do
    local wasm="$DIST/$v-release.wasm"
    log "flagcheck $v"
    run_node liftoff "$v" "$wasm" "$RESULTS/flagcheck-node-liftoff-no-wasm-tier-up-$v.json" \
      --liftoff --no-wasm-tier-up
    run_node liftoff "$v" "$wasm" "$RESULTS/flagcheck-node-liftoff-no-dynamic-tiering-$v.json" \
      --liftoff --no-wasm-tier-up --no-wasm-dynamic-tiering
    run_d8 liftoff "$v" "$wasm" "$RESULTS/flagcheck-d8-liftoff-no-wasm-tier-up-$v.json" \
      --liftoff --no-wasm-tier-up
    run_d8 liftoff "$v" "$wasm" "$RESULTS/flagcheck-d8-liftoff-no-dynamic-tiering-$v.json" \
      --liftoff --no-wasm-tier-up --no-wasm-dynamic-tiering
  done
  # How many calls of alloc_free_32(n) before the engine swaps in optimized
  # code? One process per n: V8 caches compiled modules by wire bytes.
  for v in "${TIERUP_VARIANTS[@]}"; do
    local wasm="$DIST/$v-release.wasm"
    for n in "${TIERUP_N[@]}"; do
      log "tierup $v n=$n: node, d8"
      pinned "$NODE" --allow-natives-syntax run.mjs --tierup "$n" "$wasm" \
        > "$RESULTS/tierup-node-$v-n$n.json"
      pinned "$D8" --allow-natives-syntax run-shell.js -- --tierup "$n" "$wasm" \
        > "$RESULTS/tierup-d8-$v-n$n.json"
    done
  done
}

# ---------------------------------------------------------------- shim study

# Print the call structure of one function from a wasm module: instruction
# count, number of call instructions and the callees, so the report can say
# whether the allocator fast path was inlined into the workload loop or sits
# behind a call to the __rust_alloc/__rg_alloc shims.
inspect_fn() { # wasm funcname
  local wasm=$1 fn=$2
  "$WASM_TOOLS" print "$wasm" | awk -v name="$fn" '
    $0 ~ "^  \\(func \\$" name " " { p = 1 }
    p { body[n++] = $0 }
    p && /^  \)$/ { exit }
    END {
      instrs = 0; calls = 0; callees = ""
      for (i = 1; i < n - 1; i++) {
        line = body[i]; sub(/^ +/, "", line)
        if (line ~ /^\(local /) continue
        instrs++
        if (line ~ /^call /) { calls++; sub(/^call /, "", line); callees = callees " " line }
        if (line ~ /^call_indirect/) { calls++; callees = callees " (indirect)" }
      }
      if (n == 0) { print "  function " name ": not found"; exit }
      printf "  %-16s %5d instructions, %2d calls:%s\n", name, instrs, calls, callees
    }'
}

step_shim() {
  local out="$RESULTS/shim-inspect.txt"
  : > "$out"
  for v in "${SHIM_VARIANTS[@]}"; do
    for p in "${SHIM_PROFILES[@]}"; do
      for suffix in "" "-wasmopt"; do
        local wasm="$DIST/$v-$p$suffix.wasm" tag="$p$suffix"
        log "shim $v $tag: node --no-liftoff, d8 default"
        pinned "$NODE" --allow-natives-syntax --no-liftoff run.mjs --json --reps "$REPS" \
          --only "$SHIM_WORKLOADS" --flags "--no-liftoff" "$wasm" > "$RESULTS/shim-node-turbofan-$tag-$v.json"
        pinned "$D8" --allow-natives-syntax run-shell.js -- --json --reps "$REPS" \
          --only "$SHIM_WORKLOADS" --flags "(default)" "$wasm" > "$RESULTS/shim-d8-default-$tag-$v.json"
        {
          printf '%s-%s.wasm: %d bytes, %d functions\n' "$v" "$tag" "$(stat -c %s "$wasm")" \
            "$("$WASM_TOOLS" print "$wasm" | grep -c '^  (func ')"
          inspect_fn "$wasm" alloc_free_32
          inspect_fn "$wasm" churn
          for shim in __rust_alloc __rust_dealloc __rg_alloc __rg_dealloc; do
            if "$WASM_TOOLS" print "$wasm" | grep -q "^  (func \$$shim "; then inspect_fn "$wasm" "$shim"; fi
          done
          echo
        } >> "$out"
      done
    done
  done
  cat "$out" >&2
}

# ---------------------------------------------------------------- report

step_report() {
  "$NODE" report.mjs "$RESULTS" > "$RESULTS/REPORT.md"
  log "wrote $RESULTS/REPORT.md"
}

steps=("$@")
[ ${#steps[@]} -gt 0 ] || steps=(build matrix tierup shim report)
for s in "${steps[@]}"; do
  case "$s" in
    build) step_build ;;
    matrix) step_matrix ;;
    tierup) step_tierup ;;
    shim) step_shim ;;
    report) step_report ;;
    *) echo "unknown step: $s (build matrix tierup shim report)" >&2; exit 2 ;;
  esac
done
